export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';
export const SET_TASK_INFO = 'SET_TASK_INFO';
export const RESET_TASK_INFO = 'RESET_TASK_INFO';
export const FRESH_TASKS_LIST_TRIGGER = 'FRESH_TASKS_LIST_TRIGGER';
export const RESET_FRESH_COUNT = 'RESET_FRESH_COUNT';

// alert
export const ALERT = 'ALERT';
export const HIDEALERT = 'HIDEALERT';

// popover
export const POPOVER = 'POPOVER';
export const HIDEPOPOVER = 'HIDEPOPOVER';
