export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';
export const SET_TASK_INFO = 'SET_TASK_INFO';
export const RESET_TASK_INFO = 'RESET_TASK_INFO';
export const FRESH_TASKS_LIST_TRIGGER = 'FRESH_TASKS_LIST_TRIGGER';
